services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend-dev
    environment:
      - NODE_ENV=development
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
